### ISSUE TITLE
在精灵的时间观念区间使用毁灭药水（10回合后杀死该敌人）之后，其回合数改变

### ISSUE THREAD

**Issue by one-pyy** [FrierenModForSlayTheSpire/Frieren#2]
![image](https://github.com/user-attachments/assets/3d2c6331-2fd4-444c-b1dc-533562d924a0)

**Comment by one-pyy** [comment]
以及期间使用了破灭之雷，回滚之后还是终极同调，这个算bug嘛

**Comment by one-pyy** [comment]
> 以及期间使用了破灭之雷，回滚之后还是终极同调，这个算bug嘛

好像是变换的卡牌没有变回来（）

![image](https://github.com/user-attachments/assets/7f4d8278-b076-4a86-95dd-f96739106566)
![image](https://github.com/user-attachments/assets/128c1baa-563a-429f-a3b5-a4f87aff5ff3)

**Comment by Arkalin** [comment]
不好意思，如果是其他mod内容本mod不太好支持，只能尽量支持原版内容不出问题

**Comment by one-pyy** [comment]
> 不好意思，如果是其他mod内容本mod不太好支持，只能尽量支持原版内容不出问题

哦哦抱歉，没有注意到是其他mod的
